services:
  cctv-gcc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cctv-gcc-api
    restart: unless-stopped  # always on unless stopped manually
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "task healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  sync-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync-data
    depends_on:
      cctv-gcc-api:
        condition: service_healthy
    restart: "no"
    entrypoint: ["bash", "-c"]
    volumes:
      - .:/app
    # Keep syncing data every 5 minutes
    command:
        [
          "while true; do task syncdata; sleep 300; done"
        ]